/**
 * True interop test: reads a `state.json` **generated by the real Python
 * implementation** (tests/fixtures/state.json), not a hand-written
 * approximation. This is the assertion that actually protects the contract —
 * if zot2vault's output shape drifts, this fails here rather than surfacing
 * as mysterious duplicate notes in a user's vault.
 *
 * Its Python counterpart is packages/scriptorium/tests/test_interop_spec.py.
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { VaultIndex, parseVaultState, paperEntries } from "../src/core/vault-state";
import { normalizeTitle, originIds } from "../src/core/ids";
import { emptyWork } from "../src/core/types";

const realState = readFileSync(join(__dirname, "fixtures", "state.json"), "utf-8");

describe("reading zot2vault's real output", () => {
  const state = parseVaultState(realState);

  it("parses it as a supported version", () => {
    expect(state.present).toBe(true);
    expect(state.version).toBe(1);
    expect(state.entries.length).toBeGreaterThan(0);
  });

  it("timestamps are ISO-8601 UTC with a literal Z", () => {
    // A zone-less stamp would be read as local time here and quietly skew
    // every keep-window calculation.
    for (const entry of state.entries) {
      expect(entry.generatedAt).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/);
      expect(Number.isNaN(Date.parse(entry.generatedAt))).toBe(false);
    }
  });

  it("separates author pages from papers", () => {
    const papers = paperEntries(state);
    expect(papers.every((entry) => entry.notePath.startsWith("Papers/"))).toBe(true);
    expect(state.entries.some((entry) => entry.notePath.startsWith("Authors/"))).toBe(true);
  });

  it("content hashes are sha256 hex", () => {
    for (const entry of state.entries) {
      expect(entry.contentHash).toMatch(/^[0-9a-f]{64}$/);
    }
  });
});

describe("cross-tool dedup against real output", () => {
  const index = new VaultIndex(parseVaultState(realState), normalizeTitle);

  it("recognizes a paper the plugin knows only by its OpenAlex id", () => {
    // zot2vault stored doi/zotero/openalex ids; a fetched work carries only
    // the openalex one. Recording a single id would have missed this.
    const fetched = emptyWork("W2963403868");
    fetched.ids = [{ namespace: "openalex", value: "W2963403868" }];
    expect(index.findByOrigin(originIds(fetched))).toBeDefined();
  });

  it("recognizes the same paper by DOI alone", () => {
    const fetched = emptyWork("X");
    fetched.doi = "10.5555/Attention"; // source casing; normalization must handle it
    expect(index.findByOrigin(originIds(fetched))?.notePath).toBe(
      "Papers/Attention Is All You Need.md",
    );
  });

  it("recognizes a DOI-less book by title — the gap ids alone cannot close", () => {
    // A Zotero book has only `zotero:BOOK1`, which nothing fetched from an
    // API can ever match. Title is the only bridge, which is why it's stored.
    const fetched = emptyWork("W999");
    fetched.title = "some textbook on methods";
    fetched.ids = [{ namespace: "openalex", value: "W999" }];
    expect(index.findByOrigin(originIds(fetched))).toBeUndefined();
    expect(index.findByTitle(normalizeTitle(fetched.title))?.notePath).toBe(
      "Papers/Some Textbook On Methods.md",
    );
  });

  it("does not match an unrelated paper", () => {
    const fetched = emptyWork("W111");
    fetched.doi = "10.1/completely-different";
    fetched.title = "An Entirely Unrelated Paper";
    expect(index.findByOrigin(originIds(fetched))).toBeUndefined();
    expect(index.findByTitle(normalizeTitle(fetched.title))).toBeUndefined();
  });

  it("hands over existing note names so an inbox note can avoid colliding", () => {
    expect(index.noteBaseNames()).toContain("Attention Is All You Need");
  });
});
